// settings
stopEnabled = input(title="Strategy: Stopp Loss?", type=input.bool, defval=false)
stopLossPercentage = input(title="Strategy: SL % drawback", type=input.integer, defval=80) / 100

activelyShort = input(title="Strategy: actively Short?", type=input.bool, defval=false)
stopEnabledShort = input(title="Strategy: Stopp Loss Shorts?", type=input.bool, defval=false)
stopLossPercentageShort = input(title="Strategy: SL short % rise", type=input.integer, defval=120) / 100

// stops
drawbackStop = stopEnabled ? float(src * stopLossPercentage) : na
shortStop = stopEnabledShort ? float(src * stopLossPercentageShort) : na


// order
if longCondition and stopEnabled
    strategy.exit("Stop Loss","long", stop=drawbackStop)

if (shortCondition and activelyShort and stopEnabledShort)
    strategy.exit("Cover Short","short", stop=shortStop)